GET http://localhost:3000/api/products/

### 

POST http://localhost:3000/api/products
Content-Type: application/json

{
    "name" : "Ny grej",
    "color": "Röd",
    "price" : 2000
}

### 

PUT http://localhost:3000/api/products/0
Content-Type: application/json

{
    "name" : "Ny grej 2",
    "color" : "Röd",
    "price" : 1000
}

###

DELETE http://localhost:3000/api/products/64111a08-0136-47b5-830d-bf9de2e02bfd