GET http://localhost:3000/api/products/

### 

GET http://localhost:3000/api/products/17f9b4d5-ed23-4a10-ba1a-e3a91250e918

###

POST http://localhost:3000/api/products
Content-Type: application/json

{
    "name" : "Ny grej",
    "color": "Röd",
    "price" : 2000
}

### 

PUT http://localhost:3000/api/products/64111a08-0136-47b5-830d-bf9de2e02bfd
Content-Type: application/json

{
    "name" : "Ny grej 2",
    "color" : "Röd",
    "price" : 1000
}

###

DELETE http://localhost:3000/api/products/82e7c9ee-f510-4378-9264-24920b8b967d