GET http://localhost:3000/api/products/

### 

GET http://localhost:3000/api/products/bc1b4d96-53a1-4844-8d9f-5c25cc8353d7

###

POST http://localhost:3000/api/products
Content-Type: application/json

{
    "name" : "Ny grej",
    "color": "Röd",
    "price" : 2000
}

### 

PUT http://localhost:3000/api/products/ba936213-56ee-426b-87af-c993f079ee5d
Content-Type: application/json

{
    "name" : "Ny grej editerad igen",
    "color" : "Röd",
    "price" : 1000
}

###

DELETE http://localhost:3000/api/products/bc1b4d96-53a1-4844-8d9f-5c25cc8353d7